// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORjvQL54oyYHoHpOCTY5nN_Tm1eNgjHk',
    appId: '1:574223810479:web:0e40915cd75c79944a795a',
    messagingSenderId: '574223810479',
    projectId: 'axa-project-2b21a',
    authDomain: 'axa-project-2b21a.firebaseapp.com',
    storageBucket: 'axa-project-2b21a.firebasestorage.app',
    measurementId: 'G-5025W9KVRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhHK7S9PqU25geNYVeC-LDJ0azlma0wc',
    appId: '1:574223810479:android:6c9950b6f108ae284a795a',
    messagingSenderId: '574223810479',
    projectId: 'axa-project-2b21a',
    storageBucket: 'axa-project-2b21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo61wFv0rrryRP3mN04LLH7thoESbDarM',
    appId: '1:574223810479:ios:d97aef1705d3ae704a795a',
    messagingSenderId: '574223810479',
    projectId: 'axa-project-2b21a',
    storageBucket: 'axa-project-2b21a.firebasestorage.app',
    iosBundleId: 'com.techfifo.axaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo61wFv0rrryRP3mN04LLH7thoESbDarM',
    appId: '1:574223810479:ios:d97aef1705d3ae704a795a',
    messagingSenderId: '574223810479',
    projectId: 'axa-project-2b21a',
    storageBucket: 'axa-project-2b21a.firebasestorage.app',
    iosBundleId: 'com.techfifo.axaDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBORjvQL54oyYHoHpOCTY5nN_Tm1eNgjHk',
    appId: '1:574223810479:web:0f32a0c27be9ebde4a795a',
    messagingSenderId: '574223810479',
    projectId: 'axa-project-2b21a',
    authDomain: 'axa-project-2b21a.firebaseapp.com',
    storageBucket: 'axa-project-2b21a.firebasestorage.app',
    measurementId: 'G-T96NWJEBLM',
  );
}
